export type Snapshot = {
  t: number;
  lat: number;
  lon: number;
  alt: number;
  engine_alt: number;
  r_ecef: [number, number, number];
  r_eci: [number, number, number];
  v_enu: [number, number, number];
  pad_ecef: [number, number, number];
  earth_angle: number;
  quat: [number, number, number, number];
  quat_ecef: [number, number, number, number];
  speed: number;
  speed_inertial: number;
  mach: number;
  q_dyn: number;
  aoa_deg: number;
  fuel: number;
  fuel_frac: number;
  mass: number;
  throttle: number;
  thrust: number;
  n_engines: number;
  fins: [number, number, number];
  fin_delta?: [number, number, number, number];
  gimbal: [number, number];
  rcs?: number;
  tilt_deg: number;
  heat: number;
  phase: string;
  intact: boolean;
  destroy_reason: string;
  term: string;
  terminated: boolean;
  success: boolean;
  range_h: number;
  range_gc: number;
  pos_enu: [number, number, number];
  accel_g: number;
  wind_gust: number;
  density: number;
  density_scale: number;
  periapsis_alt: number;
  scenario: string;
  weather_storm: boolean;
  weather_shear: boolean;
  destroy_enabled: boolean;
  wind_scale: number;
  cd: number;
  v_ground: [number, number, number];
  pilot?: string;
  v_slam?: number;
  slam_xyz?: number[] | Float32Array;
  plane_lock?: boolean;
  helicity_s?: number;
  lights?: number;
  relights?: number;
  weather_dir_off?: number;
  guide_until?: number;
};

export type PackedTrails = {
  generation: number;
  n: number;
  best_idx: number;
  fitnesses: number[];
  terms: string[];
  t_end: number[];
  xyz: number[] | Float32Array;
  lat: number[] | Float32Array;
  lon: number[] | Float32Array;
  counts: number[] | Uint32Array | Float64Array;
};

export type GenerationViz = {
  stamp: number;
  live: PackedTrails;
  prev: PackedTrails;
};

export type TrainInfo = {
  running: boolean;
  generation: number;
  evaluating: number;
  population: number;
  best_fitness: number;
  mean_fitness: number;
  best_ever: number;
  sigma: number;
  episodes: number;
  fitnesses: number[];
  terms: string[];
  last_successes: number;
  viz_stamp: number;
  history_best: number[];
  history_mean: number[];
  history_lands: number[];
  hidden?: number;
  n_weights?: number;
  growths?: number;
  restarts?: number;
  land_rate?: number;
  promote_ready?: boolean;
  promote_to?: number;
  mix_left?: number;
  mix_hard_pad?: boolean;
  stage?: string;
  stage_n?: number;
  stage_count?: number;
  stage_label?: string;
  live_n?: number;
  live_lands?: number;
  live_impact?: number;
  live_miss?: number;
  last_impact?: number;
  last_miss?: number;
  h_max?: number;
  h_frac?: number;
  slam_divert?: boolean;
};
