export type Snapshot = {
  t: number;
  lat: number;
  lon: number;
  alt: number;
  engine_alt: number;
  r_ecef: [number, number, number];
  r_eci: [number, number, number];
  v_enu: [number, number, number];
  pad_ecef: [number, number, number];
  earth_angle: number;
  quat: [number, number, number, number];
  quat_ecef: [number, number, number, number];
  speed: number;
  speed_inertial: number;
  mach: number;
  q_dyn: number;
  aoa_deg: number;
  fuel: number;
  fuel_frac: number;
  mass: number;
  throttle: number;
  thrust: number;
  n_engines: number;
  fins: [number, number, number];
  gimbal: [number, number];
  tilt_deg: number;
  heat: number;
  phase: string;
  intact: boolean;
  destroy_reason: string;
  term: string;
  terminated: boolean;
  success: boolean;
  range_h: number;
  range_gc: number;
  pos_enu: [number, number, number];
  accel_g: number;
  wind_gust: number;
  density: number;
  density_scale: number;
  periapsis_alt: number;
  scenario: string;
  weather_storm: boolean;
  weather_shear: boolean;
  destroy_enabled: boolean;
  wind_scale: number;
  cd: number;
  v_ground: [number, number, number];
};

export type TrainInfo = {
  running: boolean;
  generation: number;
  evaluating: number;
  population: number;
  best_fitness: number;
  mean_fitness: number;
  best_ever: number;
  sigma: number;
  episodes: number;
  fitnesses: number[];
  terms: string[];
  last_successes: number;
};
